### ISSUE TITLE
Non-functional link

### ISSUE THREAD

**Issue by GaspardG0001** [pelican-dev/panel#242] opened 2024-05-16 19:00 UTC
### Current Behavior

If I use the link at the top right of the console, I get a 404 error.
![image](https://github.com/pelican-dev/panel/assets/90980381/268e301e-3e00-461f-8a82-9eeb32513623)

### Expected Behavior

It should take me to the server admin page

### Steps to Reproduce

1. Create a server
2. Go on console and click on the button to go to the admin page

### Panel Version

v1.0.0-beta1

### Wings Version

v1.0.0-beta2

### Games and/or Eggs Affected

Minecraft (Personalized)

### Docker Image

ghcr.io/parkervcp/yolks:debian

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment] 2024-05-16 19:01
Duplicate of #197

**Closed as not planned** 2024-05-16 19:01 UTC
