### ISSUE TITLE
Admin view redirect

### ISSUE THREAD

**Issue by MayiVT** [pelican-dev/panel#272] opened 2024-05-24 10:21 UTC
### Current Behavior

When you are on a server https://panel.example.net/server/<serverID> and you press this little button to go to the admin page
![image](https://github.com/pelican-dev/panel/assets/78113457/dfcade42-c62f-4633-9bfb-eee0b372f8ca)
It redirects to the url. https://panel.araarastudios.net/admin/servers/view/<ID> 
![image](https://github.com/pelican-dev/panel/assets/78113457/99e808e5-ae88-46d0-aa65-095afb478f93)

### Expected Behavior

If you click on the button 
![image](https://github.com/pelican-dev/panel/assets/78113457/dfcade42-c62f-4633-9bfb-eee0b372f8ca)
It should take you to https://panel.araarastudios.net/admin/servers/<ID>/edit
![image](https://github.com/pelican-dev/panel/assets/78113457/cee11694-b7f7-46e3-98e3-6fa33d3548f3)

### Steps to Reproduce

1. Open the panel
2. Go to the dashboard
3. View a server
4. Press the little button

### Panel Version

1.0.0-beta2

### Wings Version

1.0.0-beta2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment] 2024-05-24 10:23
Duplicate of #197

**Closed** 2024-05-24 10:25 UTC
Labels: 🐛 bug, 👥 duplicate
