### ISSUE TITLE
The panel returns a 403 forbidden error when trying to access the API docs

### ISSUE THREAD

**Issue by axdynx** [pelican-dev/panel#258] opened 2024-05-19 16:02 UTC
### Current Behavior

![image](https://github.com/pelican-dev/panel/assets/66255038/e5d47d3e-6743-47b1-91b8-f3c69a522f98)
The panel returns a 403 forbidden error when trying to access the API docs even when we give all rights to the user www-data

### Expected Behavior

In the previous version, I could correctly access the API docs pages (which are not complete by the way)

### Steps to Reproduce

Install and configure Pelican and try to access the pages:
- https://domainname/docs/api/application
- https://domainname/docs/api/remote
- https://domainname/docs/api/client

### Panel Version

1.0.0-beta2

### Wings Version

1.0.0-beta2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment] 2024-05-19 16:03
Hey duplicate of https://github.com/pelican-dev/panel/issues/202

**Comment by axdynx** [comment] 2024-05-19 16:05
> Hey duplicate of #202 
We are not talking about the same thing, my problem is linked to the API docs and not to the API itself

**Comment by RMartinOscar** [comment] 2024-05-19 16:13
The title said Docs aswell so i think it is

**Comment by Boy132** [comment] 2024-05-19 21:15
#202 was a different error.

**Comment by lancepioch** [comment] 2024-05-22 01:42
This has been resolved now!

**Closed by lancepioch** 2024-05-22 01:42 UTC
