### ISSUE TITLE
apostrophe in .env crashes panel

### ISSUE THREAD

**Issue by ash-development** [pelican-dev/panel#575] opened 2024-09-15 22:00 UTC
### Current Behavior

i was running the installer and right after i completed it, i got a 500 error

### Expected Behavior

i expected the installation to have gone through, or error. removing the apostrophe also makes the panel run

### Steps to Reproduce

create a new installation and put an apostrophe in the panel name i.e. `ashie's panel`

### Panel Version

v1.0.0-beta8

### Wings Version

n/a

### Games and/or Eggs Affected

n/a

### Docker Image

n/a

### Error Logs

```bash
https://paste.pelistuff.com/xZsa


root@ASHubuntu:/var/www/pelican# php artisan up
The environment file is invalid!
Failed to parse dotenv file. Encountered an unexpected escape sequence at ["ashie\'s panel"].
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by ash-development** [comment] 2024-09-15 22:26
also happens when setting the sender's name in the email settings, panel instantly crashes
```sh
root@ASHubuntu:/var/www/pelican# php artisan up
The environment file is invalid!
Failed to parse dotenv file. Encountered an unexpected escape sequence at ["ashie\'s panel :3"].
```

**Comment by Boy132** [comment] 2024-09-16 06:46
Duplicate of #562

Will be fixed in the next release.

**Closed by Boy132** 2024-09-16 06:46 UTC
