### ISSUE TITLE
Bug with server edit shortcut

### ISSUE THREAD

**Issue by flvmyy** [pelican-dev/panel#299] opened 2024-05-31 03:34 UTC
### Current Behavior

When I'm on my server, in this case it's minecraft but I suppose it wouldn't matter which egg I'm using, well the thing is that when I click on this icon to edit the server through the admin panel it takes me to a path that doesn't exist.

![imagen](https://github.com/pelican-dev/panel/assets/138125743/10f658db-297b-4b3f-b685-1495469f99b1)

![imagen](https://github.com/pelican-dev/panel/assets/138125743/dc26fb8b-69f2-48d2-b8c8-b0dc4c7de8ef)

![imagen](https://github.com/pelican-dev/panel/assets/138125743/90c684c1-6c32-42e9-98a2-c25302eabc80)

Incorrect route https://panel.example.com/admin/servers/view/1
Route that should take me https://panel.example.com/admin/servers/1/edit

### Expected Behavior

It should happen that when you click on this icon

![imagen](https://github.com/pelican-dev/panel/assets/138125743/2dc1024f-c370-4cd0-b015-855d3dafa872)

I was taken directly to this page

![imagen](https://github.com/pelican-dev/panel/assets/138125743/5b01ad27-b708-427c-9931-8b8d2345eb9a)

### Steps to Reproduce

Login to your panel

![imagen](https://github.com/pelican-dev/panel/assets/138125743/f419dfd2-09e7-4e8a-b3f5-dec220bf3c77)

Click on a server

![imagen](https://github.com/pelican-dev/panel/assets/138125743/ef80ce96-cb29-4962-82c3-5bd49af4a4ed)

Click on the quick access icon for editing parameters in the administrative panel.

![imagen](https://github.com/pelican-dev/panel/assets/138125743/c0f9a844-2082-4bef-b1f2-76a68fba7333)

The error occurs

![imagen](https://github.com/pelican-dev/panel/assets/138125743/2ccfc743-b398-482a-8aab-e01fd442a3a2)

### Panel Version

Version: 1.0.0-beta2

### Wings Version

wings v1.0.0-beta2 Copyright © 2018 - 2024 Dane Everitt & Contributors

### Games and/or Eggs Affected

Paper

### Docker Image

ghcr.io/parkervcp/yolks:java_21

### Error Logs

```bash
https://paste.pelistuff.com/T5Gi

https://pteropaste.com/ubyz
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RMartinOscar** [comment] 2024-05-31 03:49
Duplicate of https://github.com/pelican-dev/panel/issues/272 https://github.com/pelican-dev/panel/issues/197
This was patched in https://github.com/pelican-dev/panel/commit/38b92ae21d0a62c088e51110194e94b28511766b just have to build from source or wait for next beta release

**Closed** 2024-05-31 04:40 UTC
