### ISSUE TITLE
Wings latest version display error

### ISSUE THREAD

**Issue by faiz36** [pelican-dev/panel#717] opened 2024-11-16 15:04 UTC
### Current Behavior

current wings version is 1.0.0-beta7 but panel says wings latest version is 1.0.0-beta13
![image](https://github.com/user-attachments/assets/7b438e15-dbb9-4b3c-ac9d-5c37edf12028)

### Expected Behavior

wings latest version 1.0.0-beta7

### Steps to Reproduce

1. install panel
2. install wings
3. add node
4. see version

### Panel Version

1.0.0-beta13

### Wings Version

1.0.0-beta7

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Boy132** [comment] 2024-11-16 15:06
Duplicate of #711

**Comment by faiz36** [comment] 2024-11-16 15:06
oh sry

**Closed by Boy132** 2024-11-16 15:06 UTC
